# Site settings
title: Greg Korte
email: gregmkorte@gmail.com
description:  > # this means to ignore newlines until "baseurl:"
  This may or may not work. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregkorte.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  gregkorte
highlighter: rouge

# Build settings
markdown: kramdown